allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
minimumReleaseAgeExclude:
  - "@cloudflare/vite-plugin@1.40.2"
  - "@cloudflare/workerd-darwin-64@1.20260611.1"
  - "@cloudflare/workerd-darwin-arm64@1.20260611.1"
  - "@cloudflare/workerd-linux-64@1.20260611.1"
  - "@cloudflare/workerd-linux-arm64@1.20260611.1"
  - "@cloudflare/workerd-windows-64@1.20260611.1"
  - "@types/node@25.9.3"
  - miniflare@4.20260611.0
  - workerd@1.20260611.1
  - wrangler@4.100.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
